apiVersion: v1
kind: Service
metadata:
  labels:
    app: django-pg-0
  name: django-pg-0
  namespace: django-pg
  resourceVersion: "181188"
  uid: 4946db56-ce42-4601-b02c-0cfa68d6fe3a
spec:
  clusterIP: 10.233.49.226
  clusterIPs:
  - 10.233.49.226
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31513
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: django-pg-0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
