name: Deploy Postgresql HELM chart

on:
  push:
    branches:
    - 'pg-deploy'
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Deploy Postgresql
      uses: 'deliverybot/helm@v1'
      with:
        release: 'postgresql'
        namespace: 'django-pg'
        chart: 'helm-charts/postgresql'
        token: '${{ github.token }}'
        value-files: >-
          [
          "values.yaml"
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
