name: Deploy Postgresql HELM chart

on:
  push:
    branches:
    - 'pg-deploy'
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: LS
      run: cat ${{ secrets.KUBECONFIG_FILE }}
    
