name: Deploy Postgresql HELM chart

on:
  push:
    branches:
    - 'pg-deploy'
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install HELM
      run: sudo snap install helm --classic
      
    - name: Create config from secret
      run: |
        mkdir ~/.kube
        echo $KFILE > ~/.kube/config
        chmod 600 ~/.kube/config
        
    - name: Deploy Postgress HELM-chart
      run: |
        kubectl 
        helm list
      
    env:
      KFILE: ${{ secrets.KUBECONFIG_FILE }}
    
      
    
