name: Deploy Postgresql HELM chart

on:
  push:
    branches:
    - 'pg-deploy'
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install HELM
      run: sudo snap install helm --classic
      
    - name: Create config from secret
      run: |
        mkdir ~/.kube
        cat << EOF > ~/.kube/config
        apiVersion: v1
        clusters:
        - cluster:
          name: cluster.local
            certificate-authority-data: ${{ secrets.CLUSTER_CA }}
            server: "51.250.25.36"
        contexts:
        - context:
          name: github-actions
            cluster: cluster.local
            user: github-actions
        current-context: github-actions
        kind: Config
        preferences: {}
        users:
        - name: github-actions
          user:
            client-certificate-data: ${{ secrets.CLIENT_CERT_DATA }}
            client-key-data: ${{ secrets.CLIENT_KEY_DATA }}
        EOF
        wc -m ~/.kube/config
        
    - name: Deploy Postgress HELM-chart
      run: |
        kubectl config view --raw
        helm list
      
    env:
      KFILE: ${{ secrets.KUBECONFIG_FILE }}
    
      
    
