name: Docker Image CI

on:
  push:
    branches: [ "deploy-pg"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Deploy Postgresql
      uses: 'deliverybot/helm@v1.7.0'
      with:
        release: 'postgresql'
        namespace: 'django-pg'
        chart: 'app'
        token: '${{ github.token }}'
        value-files: >-
          [
          "values.yaml"
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
