name: Deploy Postgresql HELM chart

on:
  push:
    branches:
    - 'pg-deploy'
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install HELM
      run: apt install helm
      
    - name: Create config from secret
      run: |
        mkdir ~/.kube
        echo $KFILE > ~./kube/config
        
    - name: Deploy Postgress HELM-chart
      run: helm
      
    env:
      KFILE: ${{ secrets.KUBECONFIG_FILE }}
    
      
    
