name: Deploy Postgresql HELM chart

on:
  push:
    branches:
    - 'pg-deploy'
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: LS
      run: |
        if [[ $FILE -eq "3" ]]
        then
          echo "It is 3!!!"
        fi
    env:
      FILE: ${{ secrets.KUBECONFIG_FILE }}
    
      
    
